# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qvk1KR0n1hJ6GV0jkG-9uLcWK-Vz0MSZ
"""

"""
============================================================
  MGPEB — Módulo de Gerenciamento de Pouso e Estabilização
          de Base
  Missão Aurora Siger — Fase 2
============================================================

Este arquivo implementa o protótipo do MGPEB conforme descrito
no relatório técnico. O sistema é organizado em quatro blocos:

  1. Definição de dados (módulos, prioridades, combustível...)
  2. Estruturas lineares (Fila, Lista Encadeada, Pilha)
  3. Algoritmos de busca e ordenação
  4. Lógica de autorização de pouso

O código usa apenas a biblioteca padrão do Python (enum,
datetime), em coerência com o requisito da atividade de
não usar bibliotecas avançadas.
============================================================
"""

from enum import Enum


# ============================================================
# 1. DEFINIÇÃO DE DADOS
# ============================================================

class Criticidade(Enum):
    """
    Níveis de criticidade dos módulos.
    Usado para classificar a importância de cada módulo
    no momento da avaliação de pouso.
    """
    CRITICO = 1
    ALTO = 2
    MEDIO = 3
    BAIXO = 4


# Lista com os nomes de todos os módulos da colônia
# A ordem aqui é a "ordem de chegada em órbita"
modulos = [
    "MGPEB",
    "Energia",
    "Habitacao",
    "Medico",
    "Cientifico",
    "Logistica e Suprimentos",
    "Mineracao",
    "Comunicacao"
]

# Nível de combustível de cada módulo, em porcentagem (%).
# A posição na lista corresponde à mesma posição em 'modulos'.
nivel_combustivel = [100, 85, 75, 90, 80, 70, 65, 95]

# Prioridade de pouso de cada módulo (1 = máxima prioridade)
prioridades = [1, 3, 4, 2, 5, 6, 7, 8]

# Massa de cada módulo, em kg (alinhada com 'modulos')
massas = [3500, 4200, 5800, 2100, 3000, 4500, 5000, 1800]

# Tipo de carga transportada por cada módulo
tipos_carga = [
    "comando",
    "energia",
    "habitacao",
    "medico",
    "cientifico",
    "suprimentos",
    "mineracao",
    "comunicacao"
]

# Criticidade de cada módulo (alinhada com 'modulos')
criticidades = [
    Criticidade.CRITICO,   # MGPEB
    Criticidade.ALTO,      # Energia
    Criticidade.CRITICO,   # Habitacao
    Criticidade.ALTO,      # Medico
    Criticidade.MEDIO,     # Cientifico
    Criticidade.MEDIO,     # Logistica
    Criticidade.BAIXO,     # Mineracao
    Criticidade.ALTO       # Comunicacao
]


# ============================================================
# 2. ESTRUTURAS LINEARES
# ============================================================

# ---- 2.1 FILA (FIFO — First In, First Out) ------------------
class Fila:
    """
    Fila de pouso dos módulos.
    Disciplina FIFO: o primeiro módulo a entrar é o primeiro
    a ser avaliado para pouso. Implementada com list para
    fins didáticos (em produção, recomenda-se collections.deque
    pela eficiência O(1) na remoção).
    """

    def __init__(self):
        self.itens = []

    def enqueue(self, item):
        """Insere um item no final da fila."""
        self.itens.append(item)

    def dequeue(self):
        """Remove e retorna o primeiro item da fila (FIFO)."""
        if not self.is_empty():
            return self.itens.pop(0)
        return None

    def is_empty(self):
        """Retorna True se a fila estiver vazia."""
        return len(self.itens) == 0

    def size(self):
        """Retorna a quantidade de itens na fila."""
        return len(self.itens)


# ---- 2.2 LISTA ENCADEADA -----------------------------------
class Node:
    """
    Nó de uma lista encadeada simples.
    Cada nó guarda um módulo, seu horário de chegada
    e uma referência para o próximo nó.
    """

    def __init__(self, modulo, horario_chegada_orbita):
        self.modulo = modulo
        self.horario_chegada_orbita = horario_chegada_orbita
        self.next = None


def push_front(head, modulo, horario_chegada_orbita):
    """
    Insere um novo nó no início da lista encadeada.
    Retorna a nova cabeça da lista.
    """
    novo_no = Node(modulo, horario_chegada_orbita)
    novo_no.next = head
    return novo_no


def print_list(head):
    """Percorre a lista encadeada e imprime os módulos em sequência."""
    atual = head
    while atual is not None:
        print(atual.modulo, end=" -> ")
        atual = atual.next
    print("END")


# ---- 2.3 PILHA (LIFO — Last In, First Out) -----------------
class Pilha:
    """
    Pilha de módulos / decisões.
    Disciplina LIFO: o último item inserido é o primeiro a sair.
    Útil para registrar histórico de decisões, onde a mais
    recente é a mais relevante para consulta imediata.
    """

    def __init__(self):
        self.itens = []

    def push(self, item):
        """Empilha um item no topo."""
        self.itens.append(item)

    def pop(self):
        """Desempilha e retorna o item do topo (LIFO)."""
        if self.itens:
            return self.itens.pop()
        return None

    def peek(self):
        """Consulta o topo da pilha sem remover."""
        if self.itens:
            return self.itens[-1]
        return None


# ============================================================
# 3. ALGORITMOS DE BUSCA
# ============================================================

def menor_combustivel(niveis):
    """
    Busca linear pelo menor nível de combustível.
    Retorna uma tupla (valor_minimo, indice_do_modulo).
    Complexidade: O(n).
    """
    menor = niveis[0]
    index_menor = 0

    for i, combustivel in enumerate(niveis):
        if combustivel < menor:
            menor = combustivel
            index_menor = i

    return menor, index_menor


def maior_prioridade(prioridades):
    """
    Busca linear pelo módulo de maior prioridade.
    Como prioridade 1 é a mais alta, procura-se o MENOR número.
    Retorna (valor_da_prioridade, indice_do_modulo).
    """
    maior = prioridades[0]
    index_maior = 0

    for i, p in enumerate(prioridades):
        if p < maior:   # menor número = maior prioridade
            maior = p
            index_maior = i

    return maior, index_maior


def buscar_tipo_carga(tipos_carga, tipo):
    """
    Busca linear por um tipo específico de carga.
    Retorna o índice do módulo, ou -1 se não encontrado.
    """
    for i, carga in enumerate(tipos_carga):
        if carga == tipo:
            return i
    return -1


# ============================================================
# 4. ALGORITMO DE ORDENAÇÃO (Selection Sort)
# ============================================================

def ordenar_fila_por_prioridade(modulos, prioridades):
    """
    Ordena a fila de pouso pela prioridade (1 = mais alta).
    Implementação didática do Selection Sort.
    Complexidade: O(n²).
    """
    # Combina prioridades e nomes em uma lista de tuplas
    fila = list(zip(prioridades, modulos))

    # Selection sort: a cada passo, encontra o menor elemento
    # restante e o coloca na posição i
    for i in range(len(fila)):
        menor = i
        for j in range(i + 1, len(fila)):
            if fila[j][0] < fila[menor][0]:
                menor = j
        # Troca o elemento da posição i com o menor encontrado
        fila[i], fila[menor] = fila[menor], fila[i]

    # Extrai apenas os nomes dos módulos, já ordenados
    fila_ordenada = []
    for _prioridade, modulo in fila:
        fila_ordenada.append(modulo)

    return fila_ordenada


# ============================================================
# 5. AUTORIZAÇÃO DE POUSO (lógica IF / ELIF / ELSE)
# ============================================================

def autorizar_pouso(prioridade, combustivel, condicoes_atmosfericas,
                    area_disponivel, integridade_sensores):
    """
    Decide se um módulo está autorizado a pousar.
    Reflete a regra booleana do circuito de portas lógicas
    descrita na Seção 2 do relatório.

    Parâmetros:
      prioridade (int): nível de prioridade (1 = máxima)
      combustivel (float): nível de combustível em %
      condicoes_atmosfericas (str): "boa", "ruim" ou "tempestade"
      area_disponivel (bool): True se a área de pouso está livre
      integridade_sensores (float): integridade em %

    Retorna uma string com o resultado da decisão.
    """

    # --- Vetos absolutos (Bloco 3 do circuito) ---
    if condicoes_atmosfericas != "boa":
        return "POUSO BLOQUEADO (condicoes atmosfericas ruins)"
    elif not area_disponivel:
        return "POUSO BLOQUEADO (area indisponivel)"
    elif integridade_sensores <= 80:
        return "POUSO BLOQUEADO (sensores comprometidos)"

    # --- Override de emergência (Bloco 2): combustível baixo ---
    elif combustivel < 20:
        return "POUSO IMEDIATO (combustivel critico)"

    # --- Condições normais (Bloco 1): prioridade alta ---
    elif prioridade <= 2:
        return "POUSO IMEDIATO (alta prioridade)"

    # --- Demais casos: aguardar na fila ---
    else:
        return "AGUARDAR NA FILA"

modulos_pousados = []     # modulos com pouso autorizado (historico)
modulos_em_alerta = []    # modulos bloqueados ou em espera


# ============================================================
# 6. EXECUÇÃO PRINCIPAL — DEMONSTRAÇÃO DAS ESTRUTURAS
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("  MGPEB — Demonstracao do prototipo")
    print("=" * 60)

    # ----- Mostra dados iniciais -----
    print("\n[1] Modulos cadastrados:")
    for i, m in enumerate(modulos):
        print(f"  - {m} (prioridade={prioridades[i]}, "
              f"combustivel={nivel_combustivel[i]}%)")

    # ----- FILA -----
    print("\n[2] Fila de pouso (FIFO):")
    fila_pouso = Fila()
    for nome in modulos:
        fila_pouso.enqueue(nome)
    print(f"  Tamanho da fila: {fila_pouso.size()}")
    print(f"  Proximo a ser avaliado: {fila_pouso.itens[0]}")

    # Simula a avaliação de 3 módulos
    print("  Retirando 3 modulos da fila para avaliacao:")
    for _ in range(3):
        m = fila_pouso.dequeue()
        print(f"    -> {m}")
    print(f"  Restam {fila_pouso.size()} modulos na fila.")

    # ----- LISTA ENCADEADA -----
    print("\n[3] Lista encadeada de modulos (ordem de chegada):")
    head = None
    # Insere no início (ordem inversa de chegada)
    for i in range(len(modulos) - 1, -1, -1):
        head = push_front(head, modulos[i], horario_chegada_orbita=i)
    print("  ", end="")
    print_list(head)

    # ----- PILHA -----
    print("\n[4] Pilha de pouso (LIFO):")
    pilha_pouso = Pilha()
    for nome in modulos:
        pilha_pouso.push(nome)
    print(f"  Topo da pilha: {pilha_pouso.peek()}")
    print("  Desempilhando todos os modulos:")
    while True:
        m = pilha_pouso.pop()
        if m is None:
            break
        print(f"    Modulo {m} pousou em Marte")

    # ----- BUSCAS -----
    print("\n[5] Algoritmos de busca:")
    valor, idx = menor_combustivel(nivel_combustivel)
    print(f"  Menor combustivel: {valor}% -> {modulos[idx]}")

    valor, idx = maior_prioridade(prioridades)
    print(f"  Maior prioridade: {valor} -> {modulos[idx]}")

    idx = buscar_tipo_carga(tipos_carga, "suprimentos")
    if idx != -1:
        print(f"  Modulo com carga 'suprimentos': {modulos[idx]}")
    else:
        print("  Tipo de carga nao encontrado")

    # ----- ORDENAÇÃO -----
    print("\n[6] Fila ordenada por prioridade (Selection Sort):")
    fila_ordenada = ordenar_fila_por_prioridade(modulos, prioridades)
    for m in fila_ordenada:
        print(f"  - {m}")

    # ----- AUTORIZAÇÃO DE POUSO -----
    print("\n[7] Autorizacao de pouso (variaveis globais simuladas):")
    # Variáveis globais do sistema (Seção 1.10 do relatório)
    condicoes_atmosfericas = "boa"
    area_disponivel = True
    integridade_sensores = 95.0

    print(f"  Atmosfera: {condicoes_atmosfericas} | "
          f"Area: {'livre' if area_disponivel else 'ocupada'} | "
          f"Sensores: {integridade_sensores}%\n")

    for modulo in fila_ordenada:
        idx = modulos.index(modulo)
        resultado = autorizar_pouso(
            prioridades[idx],
            nivel_combustivel[idx],
            condicoes_atmosfericas,
            area_disponivel,
            integridade_sensores
        )
        print(f"  {modulo:25s} -> {resultado}")

    print("\n" + "=" * 60)
    print("  Fim da demonstracao.")
    print("=" * 60)